version: 2

# NOTE: place all envvars in .autorestic.env

global:
  # forget policies sort by recency
  forget:
    # always keep at least 10 snapshots
    keep-last: 10
    # last 36 hours
    keep-hourly: 36
    # last 14 days
    keep-daily: 14
    # lasy 6 weeks
    keep-weekly: 6
    # last 12 months
    keep-monthly: 12
    # last 3 years
    keep-yearly: 3


locations:
  adguard-home:
    hooks:
      prevalidate:
        - command -v dch.sh >/dev/null
      before:
        - dch.sh stop "$AUTORESTIC_LOCATION"
      after:
        - dch.sh start "$AUTORESTIC_LOCATION"
    from: /mnt/HomelabStorage/adguardhome
    to: homelab-storage
    # top of every hour
    cron: '0 * * * *'
    # auto-prune
    forget: prune
    options:
      backup:
        tag:
          - essential
  forgejo:
    hooks:
      prevalidate:
        - command -v dch.sh >/dev/null
      before:
        - dch.sh stop "$AUTORESTIC_LOCATION"
      after:
        - dch.sh start "$AUTORESTIC_LOCATION"
    from:
      - /mnt/HomelabStorage/forgejo
      - /mnt/HomelabStorage/forgejo-runner
    to: homelab-storage
    # top of every hour
    cron: '0 * * * *'
    # auto-prune
    forget: prune
    options:
      backup:
        tag:
          - essential
  syncthing-config:
    hooks:
      before:
        - systemctl stop syncthing@syncthing.service
      after:
        - systemctl start syncthing@syncthing.service
    from: /mnt/HomelabStorage/syncthing/config
    to: homelab-storage
    # once a day at 3 AM
    cron: '0 3 * * *'
    forget: prune
    options:
      backup:
        tag:
          - essential
  # NOTE: testing this alongside docker-mc-backup
  tekxit-mc-server:
    hooks:
      prevalidate:
        - command -v rcon-cli >/dev/null
      before:
        - (rcon-cli --password "$RCON_PASSWORD" save-off && rcon-cli --password "$RCON_PASSWORD" save-all flush && sync "/home/hunterd/Documents/minecraft/servers/Tekxit4 12.0") || echo "RCON failed, server not online"
      after:
        - rcon-cli --password "$RCON_PASSWORD" save-on || echo "RCON failed, server not online"
    # NOTE: autorestic runs as root; use absolute path for this
    from: /home/hunterd/Documents/minecraft/servers/Tekxit4 12.0
    to: homelab-storage
    # top of every hour
    cron: '0 * * * *'
    forget: prune
    options:
      backup:
        exclude:
          - 'cache'
          - '*.tmp'
  # TODO: backup DVD's & Blu-Rays

backends:
  homelab-storage:
    type: local
    path: /mnt/HomelabStorage/autorestic
    # env: AUTORESTIC_HOMELAB_STORAGE_RESTIC_PASSWORD
    requireKey: true
