networks:
  caddy-proxy:
    external: true

secrets:
  couchlab-syncthing-api-key:
    file: ./secrets/couchlab-syncthing-api-key
  grafana-admin-password:
    file: ./secrets/admin-password
  white-lotus-syncthing-api-key:
    file: ./secrets/white-lotus-syncthing-api-key

services:
  # NOTE: install prometheus-node-exporter outside of docker
  prometheus:
    image: prom/prometheus:v3.11.0
    container_name: prometheus
    user: 1000:1000
    restart: unless-stopped
    command:
      - '--config.file=/prometheus/prometheus.yml'
      - '--log.level=debug'
    healthcheck:
      test: wget --timeout=15 --quiet --tries=1 --spider http://localhost:9090/ || exit 1
      interval: 15s
      timeout: 15s
      retries: 5
      start_period: 30s
      start_interval: 1s
    labels:
      wud.tag.include: '^v\d+\.\d+\.\d+$$'
      wud.link.template: 'https://github.com/prometheus/prometheus/releases/tag/v$${major}.$${minor}.$${patch}'
    networks:
      - caddy-proxy
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    secrets:
      - white-lotus-syncthing-api-key
      - couchlab-syncthing-api-key
    volumes:
      - ${PROM_DATA_DIR:?PROM_DATA_DIR is not set}:/prometheus
      - ./prometheus.yml:/prometheus/prometheus.yml
    logging:
      options:
        max-size: "10M"
        max-file: "5"

  grafana:
    image: grafana/grafana:12.2.0
    container_name: grafana
    user: 1000:1000
    depends_on:
      prometheus:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - caddy-proxy
    ports:
      - "9091:3000"
    labels:
      wud.tag.include: '^v\d+\.\d+\.\d+$$'
      wud.link.template: 'https://github.com/grafana/grafana/releases/tag/v$${major}.$${minor}.$${patch}'
    secrets:
      - grafana-admin-password
    environment:
      GF_AUTH_GENERIC_OAUTH_ENABLED: "true"
      GF_AUTH_GENERIC_OAUTH_NAME: "authentik"
      GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "${AUTHENTIK_CLIENT_ID:?AUTHENTIK_CLIENT_ID is not set}"
      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "${AUTHENTIK_CLIENT_SECRET:?AUTHENTIK_CLIENT_SECRET is not set}"
      GF_AUTH_GENERIC_OAUTH_SCOPES: "openid profile email entitlements"
      GF_AUTH_GENERIC_OAUTH_AUTH_URL: "https://auth.${BASE_DOMAIN:?BASE_DOMAIN is not set}/application/o/authorize/"
      GF_AUTH_GENERIC_OAUTH_TOKEN_URL: "https://auth.${BASE_DOMAIN:?BASE_DOMAIN is not set}/application/o/token/"
      GF_AUTH_GENERIC_OAUTH_API_URL: "https://auth.${BASE_DOMAIN:?BASE_DOMAIN is not set}/application/o/userinfo/"
      GF_AUTH_SIGNOUT_REDIRECT_URL: "https://auth.${BASE_DOMAIN:?BASE_DOMAIN is not set}/application/o/grafana/end-session/"
      # Optionally enable auto-login (bypasses Grafana login screen)
      GF_AUTH_OAUTH_AUTO_LOGIN: "true"
      # Optionally map user groups to Grafana roles
      GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: "contains(entitlements[*], 'Grafana Admins') && 'Admin' || contains(entitlements[*], 'Grafana Editors') && 'Editor' || 'Viewer'"
      # Required if Grafana is running behind a reverse proxy
      GF_SERVER_ROOT_URL: "https://grafana.${BASE_DOMAIN:?BASE_DOMAIN is not set}"
      GF_SECURITY_ADMIN_PASSWORD__FILE: /run/secrets/grafana-admin-password
    # NOTE: I highly recommend putting this on an SSD
    volumes:
      - ${GRAFANA_DATA_DIR:?GRAFANA_DATA_DIR is not set}:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini
