global:
  scrape_interval: 15s

  external_labels:
    instance: 'couchlab'

scrape_configs:
  - job_name: authentik
    scheme: https
    metrics_path: '/v1/authentik'
    static_configs:
      - targets: ['bbg-metrics.couchlab.me']

  # TODO: setup metrics.couchlab.me
  # /bbg/*
  # /fangbox/*
  # etc..
  # lock the entire thing to local IP only, maybe even just Fangbox IP only
  - job_name: caddy
    scheme: https
    metrics_path: '/v1/caddy'
    static_configs:
      - targets: ['bbg-metrics.couchlab.me']

  - job_name: cAdvisor
    scheme: https
    metrics_path: /v1/cAdvisor
    metric_relabel_configs:
      - source_labels: ['container_label_com_docker_swarm_service_name']
        target_label: 'service'
      - source_labels: ['name']
        target_label: 'container'
    static_configs:
      - targets: ['fangbox-metrics.couchlab.me', 'bbg-metrics.couchlab.me']

  - job_name: minecraft
    scheme: https
    metrics_path: /v1/mc/craftoria
    static_configs:
      - targets: ['bbg-metrics.couchlab.me']
        labels:
          application: 'mc'
          instance: craftoria

  - job_name: pihole
    scheme: https
    metrics_path: '/v1/pihole'
    static_configs:
      - targets: ['bbg-metrics.couchlab.me']

  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: node
    scrape_interval: 5s
    scheme: https
    metrics_path: /v1/node-exporter
    static_configs:
      - targets: ['fangbox-metrics.couchlab.me', 'lotus-metrics.couchlab.me', 'bbg-metrics.couchlab.me']

