global:
  scrape_interval: 15s

  external_labels:
    instance: 'couchlab'

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: syncthing
    static_configs:
      - targets: ['couchlab_syncthing_exporter:9093', 'white_lotus_syncthing_exporter:9094']

  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: traefik
    static_configs:
      - targets: ['traefik:8080']

  - job_name: node
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:9100', 'white-lotus.internal:9100']

