global:
  scrape_interval: 15s

  external_labels:
    instance: 'couchlab'

scrape_configs:
  - job_name: adguard-home
    static_configs:
      - targets: ['adguard-exporter:9618']

  - job_name: cAdvisor
    metric_relabel_configs:
      - source_labels: ['container_label_com_docker_swarm_service_name']
        target_label: 'service'
      - source_labels: ['name']
        target_label: 'container'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: traefik
    static_configs:
      - targets: ['traefik:8080']

  - job_name: node
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:9100', 'white-lotus.internal:9100']

