version: 2

# NOTE: place all envvars in .autorestic.env

global:
  # forget policies sort by recency
  forget:
    # always keep at least 10 snapshots
    keep-last: 10
    # last 48 hours
    keep-hourly: 48
    # last 14 days
    keep-daily: 14
    # lasy 6 weeks
    keep-weekly: 6
    # last 12 months
    keep-monthly: 12
    # last 3 years
    keep-yearly: 3


locations:
  forgejo:
    from: /mnt/HomelabStorage/forgejo
    to: homelab-storage
    # every half hour
    cron: '*/30 * * * *'
    # auto-prune
    forget: prune
    options:
      backup:
        tag:
          - essential
  # NOTE: testing this alongside docker-mc-backup
  tekxit-mc-server:
    hooks:
      prevalidate:
        - command -v rcon-cli >/dev/null
      before:
        - (rcon-cli --password "$RCON_PASSWORD" save-off && rcon-cli --password "$RCON_PASSWORD" save-all flush) || echo "RCON failed, server not online"
      after:
        - rcon-cli --password "$RCON_PASSWORD" save-on || echo "RCON failed, server not online"
      failure:
        - echo "Something went wrong"
        - rcon-cli --password "$RCON_PASSWORD" save-on || echo "RCON failed, server not online"
    from: ~/Documents/minecraft/servers/Tekxit4 12.0
    to: homelab-storage
    # top of every hour
    cron: '0 * * * *'
    forget: prune
    options:
      backup:
        exclude:
          - 'cache'
          - '*.tmp'
  # TODO: backup DVD's & Blu-Rays

backends:
  homelab-storage:
    type: local
    path: /mnt/HomelabStorage/autorestic
    # env: AUTORESTIC_HOMELAB_STORAGE_RESTIC_PASSWORD
    requireKey: true
