networks:
  searxng:
    driver: bridge

volumes:
  valkey-data2: {}

services:
  redis:
    container_name: redis
    image: docker.io/valkey/valkey:8-alpine
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    networks:
      - searxng
    volumes:
      - valkey-data2:/data
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    networks:
      - searxng
    ports:
      - "127.0.0.1:8180:8080"
    volumes:
      - ./config:/etc/searxng:rw
      - ./docker-init.sh:/docker-entrypoint-initdb.d/init.sh
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:?SEARXNG_HOSTNAME is not set}/
      - UWSGI_WORKERS=${SEARXNG_UWSGI_WORKERS:-4}
      - UWSGI_THREADS=${SEARXNG_UWSGI_THREADS:-4}
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
