services:
  cloudflared:
    pull_policy: always
    restart: unless-stopped
    image: cloudflare/cloudflared:latest
    entrypoint: cloudflared
    command: tunnel --no-autoupdate run --token $TOKEN
    network_mode: host
