volumes:
    postgres: {}

services:
  db:
    image: docker.io/library/postgres:14
    shm_size: "128m"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    ports:
        - "54321:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
