networks:
  forgejo:
    external: false

services:
  server:
    image: codeberg.org/forgejo/forgejo:11
    container_name: forgejo-server
    restart: unless-stopped
    environment:
      - USER_UID=${GIT_UID:?GIT_UID is not set to git user ID}
      - USER_GIT=${GIT_GID:?GIT_GID is not set to git group ID}

      - FORGEJO__database__DB_TYPE=sqlite3
      # WARN: db path is inside container
      - FORGEJO__database__PATH=/data/forgejo.db
      - FORGEJO__openid___ENABLE_OPENID_SIGNIN=false
      - FORGEJO__service__DISABLE_REGISTRATION=true
      - FORGEJO__service__REQUIRE_SIGNIN_VIEW=true
      - FORGEJO__ui__SHOW_USER_EMAIL=false

      # required for SSH cloning to work
      - FORGEJO__server__SSH_DOMAIN=${SSH_DOMAIN}
      - FORGEJO__server__ROOT_URL=${ROOT_URL:?ROOT_URL is not set}
    networks:
      - forgejo
    ports:
      - "127.0.0.1:${FORGEJO_PORT:-3300}:3000"
      - "127.0.0.1:${SSH_PORT:-2221}:22"
    volumes:
      - ${FORGEJO_DATA_PATH:?FORGEJO_DATA_PATH not set}:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
