networks:
  cloudflared:
    external: true
  traefik-proxy:
    external: true

services:
  server:
    image: codeberg.org/forgejo/forgejo:11
    container_name: forgejo-server
    restart: unless-stopped
    environment:
      - USER_UID=${GIT_UID:?GIT_UID is not set to git user ID}
      - USER_GIT=${GIT_GID:?GIT_GID is not set to git group ID}

      - FORGEJO__database__DB_TYPE=sqlite3
      # WARN: db path is inside container
      - FORGEJO__database__PATH=/data/forgejo.db
      - FORGEJO__openid___ENABLE_OPENID_SIGNIN=false
      - FORGEJO__service__DISABLE_REGISTRATION=true
      - FORGEJO__service__REQUIRE_SIGNIN_VIEW=true
      - FORGEJO__ui__SHOW_USER_EMAIL=false

      # required for SSH cloning to work
      - FORGEJO__server__SSH_DOMAIN=${SSH_DOMAIN}
      - FORGEJO__server__ROOT_URL=https://forgejo.${TRAEFIK_BASE_DOMAIN:?TRAEFIK_BASE_DOMAIN is not set}
    labels:
      traefik.enable: true
      traefik.docker.network: traefik-proxy
      traefik.http.routers.forgejo.entrypoints: http
      traefik.http.routers.forgejo.rule: Host(`forgejo.${TRAEFIK_BASE_DOMAIN:?TRAEFIK_BASE_DOMAIN is not set}`)
      traefik.http.middlewares.forgejo-https-redirect.redirectscheme.scheme: https
      traefik.http.routers.forgejo.middlewares: forgejo-https-redirect
      traefik.http.routers.forgejo-secure.entrypoints: https
      traefik.http.routers.forgejo-secure.rule: Host(`forgejo.${TRAEFIK_BASE_DOMAIN:?TRAEFIK_BASE_DOMAIN is not set}`)
      traefik.http.routers.forgejo-secure.tls: true
      traefik.http.routers.forgejo-secure.tls.certresolver: cloudflare
      traefik.http.routers.forgejo-secure.service: forgejo
      traefik.http.services.forgejo.loadbalancer.server.port: 3000
    networks:
      # for ssh
      - cloudflared
      # for https
      - traefik-proxy
    volumes:
      - ${FORGEJO_DATA_PATH:?FORGEJO_DATA_PATH not set}:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
