services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:10.10.7
    container_name: jellyfin
    restart: unless-stopped
    runtime: nvidia
    healthcheck:
      test: curl -i http://localhost:8096/health
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 30s
      start_interval: 5s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    # NOTE: if you get 'CUDA device not found' or something similar, uncomment these
    # Your system might not have all of these, just comment out the ones that give errors.
    # Check for GPU access with: docker exec -it jellyfin nvidia-smi
    devices:
      # - /dev/nvidia-caps:/dev/nvidia-caps
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-modeset:/dev/nvidia-modeset
      - /dev/nvidia-uvm:/dev/nvidia-uvm
      - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools
    labels:
      traefik.enable: true
      traefik.http.routers.jellyfin.entrypoints: https
      traefik.http.routers.jellyfin.rule: Host(`jellyfin.${TRAEFIK_BASE_DOMAIN:?TRAEFIK_BASE_DOMAIN is not set}`)
      traefik.http.routers.jellyfin.tls: true
      traefik.http.routers.jellyfin.tls.certresolver: cloudflare
      traefik.http.routers.jellyfin.service: jellyfin

      traefik.http.services.jellyfin.loadbalancer.server.port: 8096
      traefik.http.services.jellyfin.loadbalancer.healthcheck.path: /health

      wud.tag.include: '^(version-)?(\d+\.\d+\.\d+)(.*)$$'
      # exclude tags that:
      # - start with a date (YYYY-MM-dd)
      # - start with amd64, arm64, amd64v8, or arm64v8
      # - contain "latest" or "nightly"
      # - end with an Ubuntu version identifier (e.g. ubu2404)
      #   - not ALL ubuntu tags are ignored, just most
      # - end with an lsio version identifier (e.g. ls305)
      wud.tag.exclude: '^((20\d{2}\.\d{1,2}\.\d{1,2})|((amd|arm)64(v8)?-)?((latest|nightly)-?)(version-)?(\d+(\.\d+\.\d+)?(ubu\d+(-ls\d+)?))?)$$'
      # extract the major, minor, and patch from the allowable patterns, e.g.:
      # - version-10.11.0ubu2404
      # - version-10.11.0
      # - 10.11.0ubu2404
      # - 10.11.0
      wud.tag.transform: '^(version-)?(\d+\.\d+\.\d+)(.*)$$ => $$2'
      wud.link.template: 'https://github.com/jellyfin/jellyfin/releases/tag/v$${major}.$${minor}.$${patch}'
    network_mode: host
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      PUID: ${JELLYFIN_UID:?JELLYFIN_UID is not set}
      PGID: ${JELLYFIN_GID:?JELLYFIN_GID is not set}
      TZ: ${TZ:-Etc/UTC}
    volumes:
      - ${JELLYFIN_CONFIG_DIR:?JELLYFIN_CONFIG_DIR is not set}:/config
      - ${JELLYFIN_DATA_DIR:?JELLYFIN_DATA_DIR is not set}:/data
    # ports:
    #   - 8096:8096
    #   - 7359:7359/udp
    #   - 1900:1900/udp
