networks:
  wud-net:
    driver: bridge
  traefik-proxy:
    external: true

secrets:
  codeberg-username:
    file: ./secrets/codeberg-username
  codeberg-password:
    file: ./secrets/codeberg-password
  lscr-private-username:
    file: ./secrets/lscr-private-username
  lscr-private-token:
    file: ./secrets/lscr-private-token

services:
  socket-proxy:
    image: lscr.io/linuxserver/socket-proxy:latest
    container_name: wud-socket-proxy
    healthcheck:
      test: wget --quiet --tries=1 --spider http://localhost:2375/_ping || exit 1
      interval: 1m
      timeout: 30s
      retries: 5
      start_period: 10s
      start_interval: 1s
    environment:
      CONTAINERS: 1
      IMAGES: 1
      INFO: 1
      TZ: ${TZ:-Etc/UTC}
    labels:
      wud.tag.include: latest
      wud.watch.digest: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - wud-net
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /run

  whatsupdocker:
    image: ghcr.io/getwud/wud:8.1.1
    container_name: wud
    restart: unless-stopped
    depends_on:
      socket-proxy:
        condition: service_healthy
    environment:
      WUD_REGISTRY_LSCR_PUBLIC_USERNAME__FILE: /run/secrets/lscr-private-username
      WUD_REGISTRY_LSCR_PUBLIC_TOKEN__FILE: /run/secrets/lscr-private-token

      WUD_REGISTRY_FORGEJO_CODEBERG_URL: https://codeberg.org
      WUD_REGISTRY_FORGEJO_CODEBERG_LOGIN__FILE: /run/secrets/codeberg-username
      WUD_REGISTRY_FORGEJO_CODEBERG_PASSWORD__FILE: /run/secrets/codeberg-password

      WUD_REGISTRY_FORGEJO_CODEBERGMIRROR_URL: https://code.forgejo.org
      WUD_REGISTRY_FORGEJO_CODEBERGMIRROR_LOGIN__FILE: /run/secrets/codeberg-username
      WUD_REGISTRY_FORGEJO_CODEBERGMIRROR_PASSWORD__FILE: /run/secrets/codeberg-password

      WUD_TRIGGER_HTTP_N8N_URL: ${N8N_WEBHOOK_URL:?N8N_WEBHOOK_URL is not set}

      WUD_WATCHER_DOCKER_HOST: wud-socket-proxy
      WUD_WATCHER_DOCKER_PORT: 2375
      WUD_WATCHER_DOCKER_SOCKET: tcp://wud-socket-proxy
    labels:
      traefik.enable: true
      traefik.docker.network: traefik-proxy
      traefik.http.routers.wud.entrypoints: https
      traefik.http.routers.wud.middlewares: default-security-headers@file
      traefik.http.routers.wud.rule: Host(`wud.${TRAEFIK_BASE_DOMAIN:?TRAEFIK_BASE_DOMAIN is not set}`)
      traefik.http.routers.wud.tls: true
      traefik.http.routers.wud.tls.certresolver: cloudflare
      traefik.http.routers.wud.service: wud

      traefik.http.services.wud.loadbalancer.server.port: 3000

      wud.tag.include: '^\d+\.\d+\.\d+$$'
      wud.link.template: 'https://github.com/getwud/wud/releases/tag/$${major}.$${minor}.$${patch}'
    networks:
      - traefik-proxy
      - wud-net
    secrets:
      - codeberg-username
      - codeberg-password
      - lscr-private-token
      - lscr-private-username
