services:
    iSponsorBlockTV:
        image: ghcr.io/dmunozv04/isponsorblocktv:v2.6.0
        user: ${ISBTV_UID:-1000}:${ISBTV_GID:-1000}
        container_name: iSponsorBlockTV
        restart: unless-stopped
        network_mode: host
        labels:
            wud.tag.include: '^v\d\.\d\.\d$$'
            wud.link.template: 'https://github.com/dmunozv04/iSponsorBlockTV/releases/tag/v$${major}.$${minor}.$${patch}'
        volumes:
          - ${DATA_DIR:?DATA_DIR is not set}:/app/data
